/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala library project to get you started.
 * For more details take a look at the Scala plugin chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.0.1/userguide/scala_plugin.html
 */

plugins {
    // Apply the scala plugin to add support for Scala
    scala

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.scala-lang:scala-library:2.11.12")

    implementation("org.apache.spark:spark-core_2.11:2.1.2")
    implementation("org.apache.spark:spark-sql_2.11:2.1.2")
    implementation("org.apache.spark:spark-hive_2.11:2.1.2")
    implementation("org.apache.spark:spark-sql-kafka-0-10_2.11:2.1.2")
    implementation("org.apache.spark:spark-streaming_2.11:2.1.2")
    implementation("org.apache.spark:spark-streaming-kafka-0-10_2.11:2.1.2")

    implementation("com.typesafe:config:1.4.0")
    implementation("org.apache.logging.log4j:log4j-api:2.13.0")
    implementation("org.apache.logging.log4j:log4j-core:2.13.0")

    testImplementation("org.scalatest:scalatest_2.11:3.1.0")

    testRuntimeOnly("org.scala-lang.modules:scala-xml_2.11:1.2.0")
}
